version: '2'

volumes:
  orderer.msc.com:
  peer0.org1.msc.com:
  peer1.org1.msc.com:
  peer0.org2.msc.com:
  peer0.org3.msc.com:
  peer1.org3.msc.com:
  peer2.org3.msc.com:


networks:
  msc:

services:

  ca0:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org1
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7054
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../organizations/fabric-ca/org1:/etc/hyperledger/fabric-ca-server
    container_name: ca_org1
    networks:
      - msc

  ca1:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org2
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=8054
    ports:
      - "8054:8054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../organizations/fabric-ca/org2:/etc/hyperledger/fabric-ca-server
    container_name: ca_org2
    networks:
      - msc


  ca2:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org3
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=9054
    ports:
      - "9054:9054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../organizations/fabric-ca/org2:/etc/hyperledger/fabric-ca-server
    container_name: ca_org3
    networks:
      - msc


  ca3:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-orderer
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=10054
    ports:
      - "10054:10054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../organizations/fabric-ca/ordererOrg:/etc/hyperledger/fabric-ca-server
    container_name: ca_orderer
    networks:
      - msc


    orderer.msc.com:
      container_name: orderer.msc.com
      image: hyperledger/fabric-orderer:$IMAGE_TAG
      environment:
        - FABRIC_LOGGING_SPEC=INFO
        - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
        - ORDERER_GENERAL_LISTENPORT=7050
        - ORDERER_GENERAL_GENESISMETHOD=file
        - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
        - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
        - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
        # enabled TLS
        - ORDERER_GENERAL_TLS_ENABLED=true
        - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
        - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
        - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
        - ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR=1
        - ORDERER_KAFKA_VERBOSE=true
        - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
        - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
        - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      working_dir: /opt/gopath/hyperledger
      command: orderer
      volumes:
          - ../system-genesis-block/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
          - ../organizations/ordererOrganizations/msc.com/orderers/orderer.msc.com/msp:/var/hyperledger/orderer/msp
          - ../organizations/ordererOrganizations/msc.com/orderers/orderer.msc.com/tls/:/var/hyperledger/orderer/tls
          - orderer.msc.com:/var/hyperledger/production/orderer
      ports:
        - 7050:7050
      networks:
        - msc

    peer0.org1.msc.com:
      container_name: peer0.org1.msc.com
      image: hyperledger/fabric-peer:$IMAGE_TAG
      environment:
        - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
        # the following setting starts chaincode containers on the same
        # bridge network as the peers
        - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_msc
        - FABRIC_LOGGING_SPEC=INFO
        - CORE_PEER_TLS_ENABLED=true
        - CORE_PEER_GOSSIP_USELEADERELECTION=true
        - CORE_PEER_GOSSIP_ORGLEADER=false
        - CORE_PEER_PROFILE_ENABLED=true
        - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
        - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
        - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
        # Peer specific variabes
        - CORE_PEER_ID=peer0.org1.msc.com
        - CORE_PEER_ADDRESS=peer0.org1.msc.com:7051
        - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
        - CORE_PEER_CHAINCODEADDRESS=peer0.org1.msc.com:7052
        - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
        - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org1.msc.com:7061
        - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.msc.com:7051
        - CORE_PEER_LOCALMSPID=Org1MSP
      volumes:
          - /var/run/:/host/var/run/
          - ../organizations/peerOrganizations/org1.msc.com/peers/peer0.org1.msc.com/msp:/etc/hyperledger/fabric/msp
          - ../organizations/peerOrganizations/org1.msc.com/peers/peer0.org1.msc.com/tls:/etc/hyperledger/fabric/tls
          - peer0.org1.msc.com:/var/hyperledger/production
      working_dir: /opt/gopath/hyperledger/peer
      command: peer node start
      ports:
        -7051:7051
      networks:
        - msc     

    peer1.org1.msc.com:
      container_name: peer1.org1.msc.com
      image: hyperledger/fabric-peer:$IMAGE_TAG
      environment:
        - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
        - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_msc
        - FABRIC_LOGGING_SPEC=INFO
        - CORE_PEER_TLS_ENABLED=true
        - CORE_PEER_GOSSIP_USELEADERELECTION=true
        - CORE_PEER_GOSSIP_ORGLEADER=false
        - CORE_PEER_PROFILE_ENABLED=true
        - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
        - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
        - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt

        - CORE_PEER_ID=peer1.org1.msc.com
        - CORE_PEER_ADDRESS=peer1.org1.msc.com:7061
        - CORE_PEER_LISTENADDRESS=0.0.0.0:7061
        - CORE_PEER_CHAINCODEADDRESS=peer0.org1.msc.com:7062
        - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7062
        - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.msc.com:7051
        - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org1.msc.com:7061
        - CORE_PEER_LOCALMSPID=Org1MSP
      volumes:
          - /var/run/:/host/var/run/
          - ../organizations/peerOrganizations/org1.msc.com/peers/peer1.org1.msc.com/msp:/etc/hyperledger/fabric/msp
          - ../organizations/peerOrganizations/org1.msc.com/peers/peer1.org1.msc.com/tls:/etc/hyperledger/fabric/tls
          - peer1.org1.msc.com:/var/hyperledger/production
      working_dir: /opt/gopath/hyperledger/peer
      command: peer node start
      ports:
        -7061:7061
      networks:
        - msc

    
    peer0.org2.msc.com:
      container_name: peer0.org2.msc.com
      image: hyperledger/fabric-peer:$IMAGE_TAG
      environment:
        - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
        - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_msc
        - FABRIC_LOGGING_SPEC=INFO
        - CORE_PEER_TLS_ENABLED=true
        - CORE_PEER_GOSSIP_USELEADERELECTION=true
        - CORE_PEER_GOSSIP_ORGLEADER=false
        - CORE_PEER_PROFILE_ENABLED=true
        - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
        - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
        - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt

        - CORE_PEER_ID=peer0.org2.msc.com
        - CORE_PEER_ADDRESS=peer0.org2.msc.com:8051
        - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
        - CORE_PEER_CHAINCODEADDRESS=peer0.org2.msc.com:8052
        - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
        - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org2.msc.com:8051
        - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.msc.com:8051
        - CORE_PEER_LOCALMSPID=Org2MSP
      volumes:
          - /var/run/:/host/var/run/
          - ../organizations/peerOrganizations/org2.msc.com/peers/peer0.org2.msc.com/msp:/etc/hyperledger/fabric/msp
          - ../organizations/peerOrganizations/org2.msc.com/peers/peer0.org2.msc.com/tls:/etc/hyperledger/fabric/tls
          - peer0.org2.msc.com:/var/hyperledger/production
      working_dir: /opt/gopath/hyperledger/peer
      command: peer node start
      ports:
        -8051:8051
      networks:
        - msc     


    peer0.org3.msc.com:
      container_name: peer0.org3.msc.com
      image: hyperledger/fabric-peer:$IMAGE_TAG
      environment:
        - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
        - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_msc
        - FABRIC_LOGGING_SPEC=INFO
        - CORE_PEER_TLS_ENABLED=true
        - CORE_PEER_GOSSIP_USELEADERELECTION=true
        - CORE_PEER_GOSSIP_ORGLEADER=false
        - CORE_PEER_PROFILE_ENABLED=true
        - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
        - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
        - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt

        - CORE_PEER_ID=peer0.org3.msc.com
        - CORE_PEER_ADDRESS=peer0.org3.msc.com:9051
        - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
        - CORE_PEER_CHAINCODEADDRESS=peer0.org3.msc.com:9052
        - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
        - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org3.msc.com:9061
        - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org3.msc.com:9051
        - CORE_PEER_LOCALMSPID=Org3MSP
      volumes:
          - /var/run/:/host/var/run/
          - ../organizations/peerOrganizations/org3.msc.com/peers/peer0.org3.msc.com/msp:/etc/hyperledger/fabric/msp
          - ../organizations/peerOrganizations/org3.msc.com/peers/peer0.org3.msc.com/tls:/etc/hyperledger/fabric/tls
          - peer0.org3.msc.com:/var/hyperledger/production
      working_dir: /opt/gopath/hyperledger/peer
      command: peer node start
      ports:
        - 9051:9051
      networks:
        - msc     


    peer1.org3.msc.com:
      container_name: peer1.org3.msc.com
      image: hyperledger/fabric-peer:$IMAGE_TAG
      environment:
        - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
        - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_msc
        - FABRIC_LOGGING_SPEC=INFO
        - CORE_PEER_TLS_ENABLED=true
        - CORE_PEER_GOSSIP_USELEADERELECTION=true
        - CORE_PEER_GOSSIP_ORGLEADER=false
        - CORE_PEER_PROFILE_ENABLED=true
        - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
        - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
        - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt

        - CORE_PEER_ID=peer1.org3.msc.com
        - CORE_PEER_ADDRESS=peer1.org3.msc.com:9061
        - CORE_PEER_LISTENADDRESS=0.0.0.0:9061
        - CORE_PEER_CHAINCODEADDRESS=peer1.org3.msc.com:9062
        - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9062
        - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org3.msc.com:9051
        - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org3.msc.com:9061
        - CORE_PEER_LOCALMSPID=Org3MSP
      volumes:
          - /var/run/:/host/var/run/
          - ../organizations/peerOrganizations/org3.msc.com/peers/peer1.org3.msc.com/msp:/etc/hyperledger/fabric/msp
          - ../organizations/peerOrganizations/org3.msc.com/peers/peer1.org3.msc.com/tls:/etc/hyperledger/fabric/tls
          - peer1.org3.msc.com:/var/hyperledger/production
      working_dir: /opt/gopath/hyperledger/peer
      command: peer node start
      ports:
        -9061:9061
      networks:
        - msc     


    peer2.org3.msc.com:
      container_name: peer2.org3.msc.com
      image: hyperledger/fabric-peer:$IMAGE_TAG
      environment:
        - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
        - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_msc
        - FABRIC_LOGGING_SPEC=INFO
        - CORE_PEER_TLS_ENABLED=true
        - CORE_PEER_GOSSIP_USELEADERELECTION=true
        - CORE_PEER_GOSSIP_ORGLEADER=false
        - CORE_PEER_PROFILE_ENABLED=true
        - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
        - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
        - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt

        - CORE_PEER_ID=peer2.org3.msc.com
        - CORE_PEER_ADDRESS=peer2.org3.msc.com:9071
        - CORE_PEER_LISTENADDRESS=0.0.0.0:9071
        - CORE_PEER_CHAINCODEADDRESS=peer2.org3.msc.com:9072
        - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9072
        - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org3.msc.com:9051
        - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer2.org3.msc.com:9071
        - CORE_PEER_LOCALMSPID=Org3MSP
      volumes:
          - /var/run/:/host/var/run/
          - ../organizations/peerOrganizations/org3.msc.com/peers/peer2.org3.msc.com/msp:/etc/hyperledger/fabric/msp
          - ../organizations/peerOrganizations/org3.msc.com/peers/peer2.org3.msc.com/tls:/etc/hyperledger/fabric/tls
          - peer2.org3.msc.com:/var/hyperledger/production
      working_dir: /opt/gopath/hyperledger/peer
      command: peer node start
      ports:
        -9071:9071
      networks:
        - msc
